version: '3'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "3030:3030"
    command: npm run start
    networks:
      - app-network

  client:
    container_name: client
    build:
      context: .
      dockerfile: client.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
      - ./client/api:/app/client/api
    depends_on: 
      - server
    command: ["/bin/sh", "-c", "npm run dev -- --host 0.0.0.0"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
